apiVersion: v1
kind: Namespace
metadata:
  name: slack-apps
  labels:
    app.kubernetes.io/name: slack-apps
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: slack-apps
  name: coin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - apps.thor-hansen.com
    secretName: coin-crt
  rules:
  - host: apps.thor-hansen.com
    http:
      paths:
      - path: /v1/coin
        backend:
          serviceName: coin
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: slack-apps
  name: coin
  labels:
    app: coin
spec: 
  replicas: 1
  selector:
      matchLabels:
        app: coin
  template:
    metadata:
      labels:
        app: coin
    spec:
      containers:
      - name: coin
        image: quay.io/thorfour/coin:v1.0.0
        ports:
        - containerPort: 80
